# Site
name: '菜加班'
description: '菜加班，一個平凡的上班族分享生活、技術的地方！'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'ordinarycas@newbieovertime.work'
# mailchimp-list: ''
# timezone: 'Asia/Taipei'

include: ["_pages"]
permalink: /blog/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jhan:
      name:           Jhan
      site:           https://newbieovertime.work
      avatar:         https://web3-images-api.kibalabs.com/v1/accounts/0xdA3e7efAfB0E3de410ACA788300F0d43948b88e5/image
      bio:            "Hi, I am Jhan, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          ordinarycas@newbieovertime.work
      # twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jhan
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]