# Site
name: '菜加班 NewbieOvertime'
description: '菜加班，一個上班族分享生活、技術的地方，也是一個專門為新手或初學者提供相關資訊和知識的部落格。在這提供各種各樣的教學文章和指南，幫助初學者從基礎開始學習各種領域的技能和知識。目前 Podcast 主要分享自己的工作生活，也順便當週記督促自己。'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'ordinarycas@newbieovertime.work'
# mailchimp-list: ''
locale: 'zh-TW'
url: "https://newbieovertime.work" # 自己部落格的網址
drafts_dir: _drafts

include: ["_pages"]
permalink: /blog/:title/

#Collections
# collections:
#   blog:
#     output: true
#     permalink: /blog/:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jhan:
      name:           Jhan
      site:           https://newbieovertime.work
      avatar:         https://web3-images-api.kibalabs.com/v1/accounts/0xdA3e7efAfB0E3de410ACA788300F0d43948b88e5/image
      bio:            "玩點技術的系統分析師"
      email:          ordinarycas@newbieovertime.work
      # twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jhan
      avatar: https://web3-images-api.kibalabs.com/v1/accounts/0xdA3e7efAfB0E3de410ACA788300F0d43948b88e5/image
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5
paginate_path: "/blog/page:num/"


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
